import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { registerGetStatus } from "./get-status";
import { registerGetCommitHistory } from "./get-commit-history";
import { registerGetDiff } from "./get-diff";
import { registerGetBlame } from "./get-blame";
import { registerGetBranches } from "./get-branches";
import { registerGetRemotes } from "./get-remotes";
import { registerSuggestCommitMessage } from "./suggest-commit-message";
import { registerStage } from "./stage";
import { registerUnstage } from "./unstage";
import { registerCommit } from "./commit";
import { registerPush } from "./push";
import { registerPull } from "./pull";
import { registerCheckout } from "./checkout";
import { registerCreateBranch } from "./create-branch";
import { registerDeleteBranch } from "./delete-branch";
import { registerMerge } from "./merge";
import { registerStash } from "./stash";
import { registerFetch } from "./fetch";
import { registerReset } from "./reset";
import { registerCherryPick } from "./cherry-pick";
import { registerRevert } from "./revert";
import { registerTag } from "./tag";

export function registerAllTools(server: McpServer): void {
  registerGetStatus(server);
  registerGetCommitHistory(server);
  registerGetDiff(server);
  registerGetBlame(server);
  registerGetBranches(server);
  registerGetRemotes(server);
  registerSuggestCommitMessage(server);
  registerStage(server);
  registerUnstage(server);
  registerCommit(server);
  registerPush(server);
  registerPull(server);
  registerCheckout(server);
  registerCreateBranch(server);
  registerDeleteBranch(server);
  registerMerge(server);
  registerStash(server);
  registerFetch(server);
  registerReset(server);
  registerCherryPick(server);
  registerRevert(server);
  registerTag(server);
}
